env: "local"

http_server:
  host: "localhost"
  port: "8080"
  timeout: 10s
  idle_timeout: 60s

firebird:
  host: 192.168.1.22
  port: 3050
  name: "/C:/Data/maximadb.fdb"
  user: "SYSDBA"

token:
  access_token_ttl: 15m
  refresh_token_ttl: 43200m
