CREATE TABLE CONTACTS (
    "ACCOUNT_ID" INTEGER PRIMARY KEY,
    "PHONE_NUMBER" VARCHAR(40),
    "EMAIL" VARCHAR(255),
    CONSTRAINT FK_CONTACTS_ACCOUNT FOREIGN KEY ("ACCOUNT_ID") REFERENCES "ACCOUNTS"("ID") ON DELETE CASCADE
);
