CREATE TABLE CLIENT_PROFILES (
    "ACCOUNT_ID" INTEGER NOT NULL,
    "ACCOUNT_NUMBER" VARCHAR(255),
    "CONTRACT_NUMBER" VARCHAR(40),
    CONSTRAINT FK_PROFILE_ACCOUNT FOREIGN KEY ("ACCOUNT_ID") REFERENCES "ACCOUNTS"("ID") ON DELETE CASCADE
);
