CREATE TABLE IF NOT EXISTS "ACCOUNTS" (
    "ID" SERIAL PRIMARY KEY,
    "LOGIN" VARCHAR(40) NOT NULL,
    "PASSWORD_HASH" BLOB NOT NULL,
    "IS_READ_ONLY" BOOLEAN DEFAULT FALSE,
    "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "CLIENT_PROFILES" (
    "ACCOUNT_ID" INTEGER NOT NULL,
    "ACCOUNT_NUMBER" VARCHAR(255),
    "CONTRACT_NUMBER" VARCHAR(40),
    CONSTRAINT FK_PROFILE_ACCOUNT FOREIGN KEY (ACCOUND_ID) REFERENCES ACCOUNTS(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "CONTACTS" (
    "ACCOUNT_ID" INTEGER PRIMARY KEY,
    "PHONE_NUMBER" VARCHAR(40),
    "EMAIL" VARCHAR(255),
    CONSTRAINT FK_CONTACTS_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUTNS(ID  ) ON DELETE CASCADE
);