version: '3.8'

services:
  backend:
    build: .
    container_name: go_backend
    restart: always
    extra_hosts:
      - "firebird-server:${DB_HOST}"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_URL=firebird-server
    depends_on:
      migrator:
        condition: service_completed_successfully
    ports:
      - "8080:8080"

  #frontend:
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

  migrator:
    image: migrate/migrate
    container_name: go_migrator
    extra_hosts:
      - "firebird_server:${DB_HOST}"
    volumes:
      - ../backend/migrations:/migrations
    command:
      - path=/migrations/
      - database=firebird://${DB_USER}:${DB_PASSWORD}@firebird-server:${DB_PORT}${DB_NAME}
      - up
    restart: on_failure

  firebird:
    image: jacobalberty/firebird:v3.0
    container_name: firebird_db
    restart: always
    ports:
      - "3050:3050"
    environment:
      - ISC_PASSWORD=masterkey
      - TZ=Europe/Moscow
    volumes:
      - ./fbdata:/firebird/data
      - ./fbbackup:/firebird/backup

