version: '3.8'

services:
  backend:
    build:
      context: ../backend/
      dockerfile: Dockerfile
    container_name: go_backend
    # restart: always
    networks:
      - billing-net
    extra_hosts:
      - "firebird-server:${FB_HOST}"
    environment:
      # Settings for FireBird databas
      - FB_HOST=firebird-server
      - FB_USER=${FB_USER}
      - FB_PASSWORD=${FB_PASSWORD}
      - FB_NAME=${FB_NAME}
      - FB_PORT=${FB_PORT}
      # Settings for the application
      - CONFIG_PATH=/app/config/docker.yaml
      - ACCESS_SECRET=${BILLING_ACCESS_SECRET}
      - REFRESH_SECRET=${BILLING_REFRESH_SECRET}
    ports:
      - "8080" # Можно пробросить создать профиль

  frontend:
    build:
      context: ../frontend/
      dockerfile: Dockerfile
      args:
        # Settings for the frontend
        - VITE_USE_MOCKS=${VITE_USE_MOCKS}
        - VITE_API_URL=/api
        - VITE_ENV=${VITE_ENV}
    container_name: frontend
    networks:
      - billing-net
    ports:
      - "80"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    networks:
      - billing-net
    # restart: always
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro,z
    depends_on:
      - backend
      - frontend

  # You can run local Container for FireBird database
  # firebird:
  #   image: jacobalberty/firebird:v5.0
  #   container_name: firebird_db
  #   restart: always
  #   ports:
  #     - "3050:3050"
  #   environment:
  #     - ISC_PASSWORD=masterkey
  #     - TZ=Europe/Moscow
  #   volumes:
  #     - ./fbdata:/firebird/data
  #     - ./fbbackup:/firebird/backup

networks:
  billing-net:
    driver: bridge