events {
    worker_connections 1024;
}

http {
    upstream backend_server {
        server backend:8080;
    }

    limit_req_zone $binary_remote_addr zone=mylimit:10m rate=10r/s;

    server {
        listen 80;
        server_name localhost;

        location /api/ {
            limit_req zone=mylimit;

            proxy_pass http://backend_server;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}